name: algo

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21.7.1
          architecture: x64

      - name: Instalar dependencias
        run: npm i

      - name: tests
        run: npm run test
